### ISSUE TITLE
Card should stick with the mouse while moving it around

### ISSUE THREAD

**Issue by juliushaertl** [juliushaertl/deck#39]
![2017-02-05-230137_640x875_scrot](https://cloud.githubusercontent.com/assets/3404133/22630263/24f464e8-ebf7-11e6-802c-5742f73a32ec.png)

Reported by  @ferdiga in #36

**Comment by juliushaertl** [comment]
Should be fixed now with #40

**Comment by matt-horwood-mayden** [comment]
Hi,

I have 0.1.1 installed and I still get the same issue, but it is looking very good.

Nextcloud 11.0.2
Nginx 1.10.3
PHP-FPM 5.6.29
MySQL 5.5.54

**Comment by juliushaertl** [comment]
@matt-horwood-mayden Looks like it is still broken on 0.1.1 but works fine on master. Anyway I'll try to release a 0.1.2 later today.

**Comment by matt-horwood-mayden** [comment]
Hi @juliushaertl 

Any news on the new version? no rush just wanted to test it out
